### PR TITLE
ISSUE#21 : Scroll to Top Button #21

### PR DESCRIPTION
**Pull request by syamjir**
Hi@JayZ6969 ,

This PR adds a  responsive "Scroll to Top" button placed near the footer.

Please review the changes and provide feedback.

### CODE REVIEW

**Comment by syamjir** [comment]
Hi@JayZ6969 , I have modified the code by adding a fixed position for the icon, making it visible only after the window height is reached with smooth animation. The icon disappears at the bottom of the page and reappears when scrolling back up.Please review the changes and provide feedback.

**Comment by JayZ6969** [comment]
@syamjir  Please give me some time. I'm busy for the next two days, won't be able to do much. I'll accept whenever I get some time :)

**Comment by syamjir** [comment]
@JayZ6969,No problem at all! Take your time, and feel free to accept whenever you're ready. Thanks for the update ! ):

**Review by JayZ6969 — COMMENTED** [review]
Button working ok.

**Pull request merged**
